### PR TITLE
Add offset to proxy and allow passing in a proxy to ScrollViewReader

### PR DESCRIPTION
**Pull request by tomatrow**
I was trying create a scroll view overlay that changes based on the content offset. 

Thanks for ScrollViewProxy.

### CODE REVIEW

**Comment by Amzd** [comment]
Hi, thanks for making a pull request! It was always the plan to add offset to the proxy so this fits right in. 

I'm not sure about the ScrollViewProxy init being public. Is that actually better? The SwiftUI 2 implementation doesn't have that and I think it's nice to make the API close to that so people don't have a hard time switching when they drop iOS 13 support.

Let me know what you think.

**Comment by tomatrow** [comment]
Hi,

That's a good point. We should match Apple's API. 

It would probably be better to just expose the `ScrollViewProxy.offset` as a binding, not `ScrollViewProxy` itself.

So an `init` method for `ScrollViewReader` might look like:

```swift 
 public init(offset: Binding<CGPoint>, @ViewBuilder content: @escaping () -> Content) {...} 
```

**Comment by Amzd** [comment]
I think offset should be a normal variable on the ScrollViewProxy, not Binding or State. If users want to set it to a Binding variable they can do that just like GeometryProxy.size (whenever the GeometryReader content closure is called you write the new value to your own variable).

I was also wondering wether SwiftUI needs the scrollview delegate. Because if we overtake the delegate we might see undefined behavior from SwiftUI.

**Comment by tomatrow** [comment]
That makes sense. I didn't even know you could bind `GeometryProxy.size` properly, but I googled, and [here it is](http://danielsaidi.com/blog/2020/03/25/bind-view-geometry-data-to-bindable-properties). That means the same thing would apply to the `ScrollViewProxy.offset`. I'll make this edit. 

Concerning the delegate, I don't see how to get updates on the offset without having a delegate. We could try to avoid undefined behavior by: 
(1) create our own delegate
(2) if the scrollview has no delegate => just assign ours 
(3) else if the scrollview already has a delegate 
    hold onto that delegate strongly and assign our delegate
    then have our delegate forward all messages to the preexisting delegate

p.s. I have branch called [preferences](https://github.com/tomatrow/ScrollViewProxy/tree/preferences) that uses preferences to tag views.

**Comment by Amzd** [comment]
I really like that bindGeometry function. We should have a bindOffset extension on ScrollView and List! 

For now we should at least throw an assert if the delegate was not nil so we know we're getting undefined behavior.

We should also set the onScroll in the initialiser, because setting it in the introspect closure means it's possible that it will set it multiple times which is not needed I think. The only thing that needs to change is the type from () -> () to (UIScrollView) -> Void

I looked at the preferences branch and I see the preference key code but I can't wrap my head around what it does. I haven't worked with preferencekeys since SwiftUI just came out. All I know is that it helps moving values up the View hierarchy. Can you give a little explanation on what you made?

I don't have access to my Mac right now but I'll update it next week if you don't have more time. Really appreciate you putting work into this!

**Comment by tomatrow** [comment]
I couldn't get it something like `bindGeometry` to work for `UIScrollView.contentOffset`. I think it has to do with how SwiftUI does state.

Throwing an assert seems much simpler.

Is this what you mean by setting `onScroll` in the initializer? That works perfectly, we can get the offset and what ever else we need.

```swift
public init(onScroll: @escaping (UIScrollView) -> Void = { _ in }, @ViewBuilder content: @escaping (ScrollViewProxy<ID>) -> Content) {
    self.content = content
    scrollDelegate = .init(onScroll: onScroll)
}
```

Moving values up the view hierarchy is exactly what we're doing. Concerning the preferences, we can replace `.id(index, scrollView: proxy)` with `.scrollId(id)`, as in the example from the readme.


Here's what the changes we make would look like in the example: 

```swift

struct ScrollViewProxySimpleExample: View {
    @State var randomInt = Int.random(in: 0 ..< 200)
    @State var offset = CGPoint()
    @State var proxy: ScrollViewProxy<Int>?
    
    var numbers: some View {
        ForEach(0 ..< 200) { index in
            VStack {
                Text("\(index)").font(.title)
                Spacer()
            }
            .padding()
            .scrollId(index)
        }
    }

    var body: some View {
        VStack {
            Text(offset.debugDescription)
            ScrollView {
                ScrollViewReader(onScroll: { scrollView in 
                    self.offset = scrollView.contentOffset 
                }) { proxy in
                    self.numbers.onAppear { self.proxy = proxy }
                }
            }
            HStack {
                Button(action: {
                    self.proxy?.scrollTo(self.randomInt, alignment: .center)
                    self.randomInt = Int.random(in: 0 ..< 200)
                }, label: {
                    Text("Go to \(self.randomInt)")
                })
                Spacer()
                Button(action: { self.proxy?.scrollTo(.top) }, label: {
                    Text("Top")
                })
                Spacer()
                Button(action: { self.proxy?.scrollTo(.center) }, label: {
                    Text("Center")
                })
                Spacer()
                Button(action: { self.proxy?.scrollTo(.bottom) }, label: {
                    Text("Bottom")
                })
            }
        }
    }
}
```

----


Okay. I think I fixed it. Now the onScroll closure is on ScrollViewProxy, and we only pass the offset.

```swift
struct ScrollViewProxySimpleExample: View {
    @State var randomInt = Int.random(in: 0 ..< 200)
    @State var offset = CGPoint()
    @State var proxy: ScrollViewProxy<Int>?

    var numbers: some View {
        ForEach(0 ..< 200) { index in
            VStack {
                Text("\(index)").font(.title)
                Spacer()
            }
            .padding()
            .scrollId(index)
        }
    }

    var body: some View {
        VStack {
            Text(offset.debugDescription)
            ScrollView {
                ScrollViewReader { (proxy: ScrollViewProxy<Int>) in 
                    self.numbers.onAppear {
                        self.proxy = proxy
                        self.proxy?.onScroll = { offset in 
                            self.offset = offset
                        }
                    }
                }
            }
            HStack {
                Button(action: {
                    self.proxy?.scrollTo(self.randomInt, alignment: .center)
                    self.randomInt = Int.random(in: 0 ..< 200)
                }, label: {
                    Text("Go to \(self.randomInt)")
                })
                Spacer()
                Button(action: { self.proxy?.scrollTo(.top) }, label: {
                    Text("Top")
                })
                Spacer()
                Button(action: { self.proxy?.scrollTo(.center) }, label: {
                    Text("Center")
                })
                Spacer()
                Button(action: { self.proxy?.scrollTo(.bottom) }, label: {
                    Text("Bottom")
                })
            }
        }
    }
}
```

**Comment by Amzd** [comment]
I added an [offset publisher](https://github.com/Amzd/ScrollViewProxy/blob/3ecd26174d68f0323ede37024058592d686c52f8/Sources/ScrollViewProxy/ScrollViewProxy.swift#L180) instead of reloading the entire ScrollViewReader.content block when the offset changes. This produced much better performance.

Closing this due to the goal of the PR being met.

**Pull request closed without merging**
